### ISSUE TITLE
"2: No such file" when uploading to sftp server

### ISSUE THREAD

**Issue by Kenajcrap** [espidev/ebackup#13]
pertinent log snippet
```
[19:34:59 INFO]: Kenajcrap issued server command: /ebackup backup
[19:34:59 INFO]: [eBackup] Starting backup...
[19:35:00 INFO]: [eBackup] Backing up world ....
[19:35:00 INFO]: [eBackup] Backing up world ....
[19:35:01 INFO]: [eBackup] Backing up world ....
[19:35:01 INFO]: [eBackup] Backing up other files...
[19:35:06 INFO]: [eBackup] Uploading backup to SFTP server...
[19:35:07 WARN]: 2: No such file
[19:35:07 WARN]:        at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2873)
[19:35:07 WARN]:        at com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:594)
[19:35:07 WARN]:        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:475)
[19:35:07 WARN]:        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:365)
[19:35:07 WARN]:        at dev.espi.ebackup.BackupUtil.uploadSFTP(BackupUtil.java:178)
[19:35:07 WARN]:        at dev.espi.ebackup.BackupUtil.doBackup(BackupUtil.java:125)
[19:35:07 WARN]:        at dev.espi.ebackup.eBackup.lambda$onCommand$1(eBackup.java:146)
[19:35:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:35:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:35:07 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:35:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[19:35:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[19:35:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[19:35:07 INFO]: [eBackup] Backup complete!
```
config.yml ([REDACTED] used to hide private information):
```
crontask: '0 0 20 * * *' 

backup-format: '{DATE}'

backup-path: 'plugins/eBackup/backups'

max-backups: 4

ftp:
    enable: true
    type: sftp # ftp for ftp, sftp for ftp over ssh
    host: '[REDACTED]'
    port: [REDACTED]
    user: '[REDACTED]'
    pass: '[REDACTED]'
    path: 'D:\Users\[REDACTED]\Documents\Backups\[REDACTED]'

backup:
    pluginjars: false # The .jar files for the plugins
    pluginconfs: true # The data folder of each plugin
    ignore: # Files to ignore and NOT backup
        - 'plugins/eBackup/backups'
        - 'plugins/dynmap'
        - 'logs'
        - 'cache'
```
pertinent sshd_config ([REDACTED] used to hide private information):
```
Match address [REDACTED]
	PasswordAuthentication yes
	ChrootDirectory D:\Users\[REDACTED]\Documents\Backups\[REDACTED]

AllowUsers [REDACTED]
```
The mc server is running on a linux box and the sftp server is running OpenSSH_for_Windows

Please, lmk if more info is required to solve this issue

**Comment by espidev** [comment]
Have you been able to use scp to test transferring a file to that exact path?

**Comment by Kenajcrap** [comment]
i'm ashamed I didn't try this before opening an issue... I can't in fact copy from that path if i use an absolute path.
I've fixed the issue temporarily by replacing the `path` with `/.` in config.yml, since I already had `ChrootDirectory D:\Users\[REDACTED]\Documents\Backups\[REDACTED]` setup to start in the desired location.
When I figure out the correct sintax for an absolute path that points to a secondary drive on a windows machine i will update this issue.
Thanks for the quick response
