### ISSUE TITLE
Can't connect to ftp

### ISSUE THREAD

**Issue by DooSHeK2** [espidev/ebackup#33]
ebackup: 1.2.0
paper-1.17.1-305
Java 16

ebackup can't connect to ftp and send files to ftp server. All credentials are ok. It was working ok and stopped working after hosting change.

```
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/INFO]: [eBackup] Uploading backup to FTP server...
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: org.apache.commons.net.ftp.FTPConnectionClosedException: Connection closed without indication.
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.__getReply(FTP.java:324)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.__getReply(FTP.java:300)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:523)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:648)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.pass(FTP.java:811)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTPClient.login(FTPClient.java:1085)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.BackupUtil.uploadFTP(BackupUtil.java:212)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.BackupUtil.doBackup(BackupUtil.java:150)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.eBackup.lambda$onCommand$1(eBackup.java:170)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:10:31] [Craft Scheduler Thread - 355 - eBackup/INFO]: [eBackup] Backup complete!
```

**Comment by espidev** [comment]
Hmm, that's quite strange that it would break after you change hosts... Do you have SSH access to the new machine? Can you use SFTP?

**Comment by DooSHeK2** [comment]
> Hmm, that's quite strange that it would break after you change hosts... Do you have SSH access to the new machine? Can you use SFTP?

When I use SFTP same error. Is there a way to display more  verbose output about error? When I google it about error it's says something about outdated java library or something. So maybe it is hosting and java problem?

**Comment by espidev** [comment]
Hmm, outdated java library...

Could you please try this build: https://drive.google.com/file/d/1VS4mBuW8xgAeIgzlIe9yhS7AHX9Ocu_g/view?usp=sharing

I updated the java libraries needed for FTP

**Comment by DooSHeK2** [comment]
> Hmm, outdated java library...
> 
> Could you please try this build: https://drive.google.com/file/d/1VS4mBuW8xgAeIgzlIe9yhS7AHX9Ocu_g/view?usp=sharing
> 
> I updated the java libraries needed for FTP

Nope, it didn't help. Still same error.

**Comment by espidev** [comment]
> When I use SFTP same error. Is there a way to display more verbose output about error? When I google it about error it's says something about outdated java library or something. So maybe it is hosting and java problem?

Could you give me the error that you get from SFTP?

**Comment by DooSHeK2** [comment]
> > When I use SFTP same error. Is there a way to display more verbose output about error? When I google it about error it's says something about outdated java library or something. So maybe it is hosting and java problem?
> 
> Could you give me the error that you get from SFTP?

```
[18:14:46] [Craft Scheduler Thread - 23 - eBackup/INFO]: [eBackup] Uploading backup to SFTP server...
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: com.jcraft.jsch.JSchException: connection is closed by foreign host
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at ebackup-1.2.0.jar//com.jcraft.jsch.Session.connect(Session.java:269)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at ebackup-1.2.0.jar//com.jcraft.jsch.Session.connect(Session.java:183)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.BackupUtil.uploadSFTP(BackupUtil.java:199)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.BackupUtil.doBackup(BackupUtil.java:148)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.eBackup.lambda$onCommand$1(eBackup.java:171)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:16:46] [Craft Scheduler Thread - 23 - eBackup/INFO]: [eBackup] Backup complete!
```
I think it won't work via sftp. When I connect using ftp client I get a popup message about some certificate mismatch or something (i don't remember exactly) and have to accept message.

**Comment by espidev** [comment]
just to be sure, you're not using FTPS right? because there isn't support for FTPS

I made another build (same link) with some timeout patches from a PR: https://drive.google.com/file/d/1VS4mBuW8xgAeIgzlIe9yhS7AHX9Ocu_g/view?usp=sharing

**Comment by DooSHeK2** [comment]
> just to be sure, you're not using FTPS right? because there isn't support for FTPS
> 
> I made another build (same link) with some timeout patches from a PR: https://drive.google.com/file/d/1VS4mBuW8xgAeIgzlIe9yhS7AHX9Ocu_g/view?usp=sharing

No I am not using SFTP, only FTP. I tried SFTP because you asked me to do.

Still same error:
```
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/INFO]: [eBackup] Uploading backup to FTP server...
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: org.apache.commons.net.ftp.FTPConnectionClosedException: Connection closed without indication.
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.getReply(FTP.java:314)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.getReply(FTP.java:719)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:514)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:635)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTP.pass(FTP.java:810)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//org.apache.commons.net.ftp.FTPClient.login(FTPClient.java:2813)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.BackupUtil.uploadFTP(BackupUtil.java:220)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.BackupUtil.doBackup(BackupUtil.java:151)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at ebackup-1.2.0.jar//dev.espi.ebackup.eBackup.lambda$onCommand$1(eBackup.java:171)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[20:57:22] [Craft Scheduler Thread - 9 - eBackup/INFO]: [eBackup] Backup complete!
```

**Comment by espidev** [comment]
FTPS is different from SFTP, I mean are you using encrypted FTP? (which is called FTPS)

**Comment by DooSHeK2** [comment]
Do you mean am I connecting via ftps:://ftp.myhost or ftp://ftp.myhost? I am connecting via FTP not FTPS. I'm connecting to the same ftp server as from the previous mc hosting.

**Comment by espidev** [comment]
You said that your FTP client said something about certificates... I thought that'd only apply to encrypted FTP. If you could check the message your client had that'd be great.

To be honest I don't have any clue why it's unable to connect simply from changing machines :c
I'm not able to duplicate the issue myself.

**Comment by DooSHeK2** [comment]
To make it clear. I had the message about the certificate when I connected to the ftp server via ftps: // to check if I can connect to the server via ftps (I thought ftps is the same as sftp :)) When I connect to the server via regular ftp there is no message (in ftp client).
![cert](https://user-images.githubusercontent.com/93473125/139949518-f2385ed4-9f13-451f-bf50-a2425faca2b4.jpg)

I have no idea either. Maybe it something in this new hosting? But how to debug it?

**Comment by espidev** [comment]
Sorry about the delay, I somehow missed the email notification...

It's hard to really debug this from here, if you are still having issues could you please just direct message me on Discord (EspiDev#2837) and we can see if we can work this out.

**Comment by DooSHeK2** [comment]
> Sorry about the delay, I somehow missed the email notification...
> 
> It's hard to really debug this from here, if you are still having issues could you please just direct message me on Discord (EspiDev#2837) and we can see if we can work this out.

Yeah sure but after a the weekend.

**Comment by espidev** [comment]
closed to inactivity
