### ISSUE TITLE
ZipException when I try to create a backup

### ISSUE THREAD

**Issue by serega404** [espidev/ebackup#40]
Hello, I'm trying to create a backup and I get this error:

>[16:11:35 WARN]: java.util.zip.ZipException: duplicate entry: world/DIM1/
[16:11:35 WARN]:  at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
[16:11:35 WARN]:  at dev.espi.ebackup.BackupUtil.zipFile(BackupUtil.java:330)
[16:11:35 WARN]:  at dev.espi.ebackup.BackupUtil.doBackup(BackupUtil.java:130)
[16:11:35 WARN]:  at dev.espi.ebackup.eBackup.lambda$onCommand$1(eBackup.java:196)
[16:11:35 WARN]:  at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[16:11:35 WARN]:  at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50)
[16:11:35 WARN]:  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:11:35 WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:11:35 WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:11:35 WARN]:  at java.lang.Thread.run(Thread.java:748)

- Core: Mohist 1.12.2 (forge + spigot)
- FTP work
- Work on a neighboring server (Paper 1.18)

Config:
- backup-path: 'plugins/eBackup/backups'
- compression-level: 5
- backup-format: 'Backup {DATE}'

**Comment by espidev** [comment]
Hmm, that's strange, do you have any "symlinks"/shortcuts anywhere that could cause the plugin to re-backup the world folder?
Specifically `world/DIM1/`

**Comment by espidev** [comment]
Could you please give https://build.espi.dev/job/ebackup/24/ a try

**Comment by serega404** [comment]
This build works without errors 👍
