### ISSUE TITLE
Can't run commands from console

### ISSUE THREAD

**Issue by nick-potts** [espidev/ebackup#5]
```
[14:16:06] [Server thread/INFO]: Starting backup...
[14:16:06] [Server thread/WARN]: Unexpected exception while parsing console command "ebackup backuplocal"
org.bukkit.command.CommandException: Unhandled exception executing command 'ebackup' in plugin eBackup v1.0.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:696) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:430) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:394) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:443) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:200) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:196) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:147) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:116) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	at dev.espi.ebackup.eBackup.onCommand(eBackup.java:129) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
	... 8 more
```

**Comment by nick-potts** [comment]
Server restart fixed it
