### ISSUE TITLE
3: permission denied

### ISSUE THREAD

**Issue by GreenArrowlol** [espidev/ebackup#51]
tried testupload to my sftp and this showed up

`[07:18:07 WARN]: 3: Permission denied
[07:18:07 WARN]:        at ebackup-1.3.1.jar//com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2873)
[07:18:07 WARN]:        at ebackup-1.3.1.jar//com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:594)
[07:18:07 WARN]:        at ebackup-1.3.1.jar//com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:475)
[07:18:07 WARN]:        at ebackup-1.3.1.jar//com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:365)
[07:18:07 WARN]:        at ebackup-1.3.1.jar//dev.espi.ebackup.BackupUtil.uploadSFTP(BackupUtil.java:243)
[07:18:07 WARN]:        at ebackup-1.3.1.jar//dev.espi.ebackup.BackupUtil.lambda$uploadTask$1(BackupUtil.java:199)
[07:18:07 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[07:18:07 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:18:07 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:18:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:18:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:18:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by espidev** [comment]
`Permission denied`, does your server have access to the folder you are writing to
