### ISSUE TITLE
Backup doesn't work (ERROR)

### ISSUE THREAD

**Issue by Nikogenia** [espidev/ebackup#63]
[18:00:00 INFO]: [eBackup] Starting backup...
[18:00:00 WARN]: java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
[18:00:00 WARN]: 	at ebackup-1.3.1.jar//dev.espi.ebackup.BackupUtil.checkMaxBackups(BackupUtil.java:45)
[18:00:00 WARN]: 	at ebackup-1.3.1.jar//dev.espi.ebackup.BackupUtil.doBackup(BackupUtil.java:86)
[18:00:00 WARN]: 	at ebackup-1.3.1.jar//dev.espi.ebackup.eBackup.lambda$loadPlugin$0(eBackup.java:137)
[18:00:00 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:00:00 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:00:00 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:00:00 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:00:00 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:00:00 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:00:00 INFO]: [eBackup] Local backup complete!

Something doesn't work! I have downloaded the plugin an hour ago from the official spigot page. But if I start a backup, this error get logged and nothing happens! Thank you for this beautiful plugin and your help!

**Comment by Nikogenia** [comment]
The problem got fixed! I don't need further help! Thank you very much for this fantastic plugin!
