### ISSUE TITLE
FTP Upload Error: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by brest21** [espidev/ebackup#64]
Running Paper 1.20.2, with ebackup 1.3.1. 

Uploading to FTP server this is the error that I get when the upload completes. The files seem to be there on my ftp server, but I am unsure if it's 100% complete as this error makes me think there's something wrong.

17.10 22:15:03 [Server] WARN java.net.SocketTimeoutException: Read timed out
17.10 22:15:03 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
17.10 22:15:03 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
17.10 22:15:03 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
17.10 22:15:03 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
17.10 22:15:03 [Server] WARN at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
17.10 22:15:03 [Server] WARN at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
17.10 22:15:03 [Server] WARN at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
17.10 22:15:03 [Server] WARN at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
17.10 22:15:03 [Server] WARN at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
17.10 22:15:03 [Server] WARN at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
17.10 22:15:03 [Server] WARN at java.base/java.io.BufferedReader.read(BufferedReader.java:183)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//org.apache.commons.net.io.CRLFLineReader.readLine(CRLFLineReader.java:58)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//org.apache.commons.net.ftp.FTP.__getReply(FTP.java:321)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//org.apache.commons.net.ftp.FTP.__getReplyNoReport(FTP.java:311)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//org.apache.commons.net.ftp.FTPClient$CSL.cleanUp(FTPClient.java:3900)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//org.apache.commons.net.ftp.FTPClient._storeFile(FTPClient.java:691)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//org.apache.commons.net.ftp.FTPClient.__storeFile(FTPClient.java:639)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//org.apache.commons.net.ftp.FTPClient.storeFile(FTPClient.java:2030)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//dev.espi.ebackup.BackupUtil.uploadFTP(BackupUtil.java:277)
17.10 22:15:03 [Server] WARN at ebackup-1.3.1.jar//dev.espi.ebackup.BackupUtil.lambda$uploadTask$1(BackupUtil.java:201)
17.10 22:15:03 [Server] WARN at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
17.10 22:15:03 [Server] WARN at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
17.10 22:15:03 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
17.10 22:15:03 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
17.10 22:15:03 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
17.10 22:15:03 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
17.10 22:15:03 [Server] INFO [eBackup] Upload of plugins/eBackup/backups/eBackup 2023-10-17 21-52-38.zip has failed.

**Comment by noyyyy** [comment]
same problem for me. I use Paper 1.20.1, with ebackup 1.3.1.
